```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Provisions DynamoDB tables
Parameters:
    stage:
        Type: String
Resources:
#########
# DynamoDB Tables
#########
    dynamodbTableCbInfo:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: accountCbAlias
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: accountCbAlias
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: '1'
                WriteCapacityUnits: '1'
            TableName: !Join [ "-", [ "talr-cbInfo", !Ref stage ] ]
            EncryptionSpecification:
                EncryptionType: KMS
                KMSMasterKeyId: !Ref kmsKey
    dynamodbTableAccountInfo:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: accountEmailAddress
                    AttributeType: S
                -
                    AttributeName: requestId
                    AttributeType: S
                -
                    AttributeName: accountId
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: accountEmailAddress
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: '1'
                WriteCapacityUnits: '1'
            GlobalSecondaryIndexes:
                -
                    IndexName: gsiRequestId
                    KeySchema:
                        -
                            AttributeName: requestId
                            KeyType: HASH
                    Projection:
                        ProjectionType: KEYS_ONLY
                    ProvisionedThroughput:
                        ReadCapacityUnits: '1'
                        WriteCapacityUnits: '1'
                -
                    IndexName: gsiAccountId
                    KeySchema:
                        -
                            AttributeName: accountId
                            KeyType: HASH
                    Projection:
                        ProjectionType: ALL
                    ProvisionedThroughput:
                        ReadCapacityUnits: '1'
                        WriteCapacityUnits: '1'
            TableName: !Join [ "-", [ "talr-accountInfo", !Ref stage ] ]
            EncryptionSpecification:
                EncryptionType: KMS
                KMSMasterKeyId: !Ref kmsKey
    dynamodbTableTaskStatus:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: requestId
                    AttributeType: S
                -
                    AttributeName: eventTimestamp
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: requestId
                    KeyType: HASH
                -
                    AttributeName: eventTimestamp
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: '1'
                WriteCapacityUnits: '1'
            StreamSpecification:
                StreamViewType: NEW_AND_OLD_IMAGES
            TableName: !Join [ "-", [ "talr-taskStatus", !Ref stage ] ]
            EncryptionSpecification:
                EncryptionType: KMS
                KMSMasterKeyId: !Ref kmsKey
    dynamodbTableNipapCfn:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: nipapAlias
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: nipapAlias
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: '1'
                WriteCapacityUnits: '1'
            TableName: !Join [ "-", [ "talr-nipapCfn", !Ref stage ] ]
            EncryptionSpecification:
                EncryptionType: KMS
                KMSMasterKeyId: !Ref kmsKey
    dynamodbTableOps:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: layer
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: layer
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: '1'
                WriteCapacityUnits: '1'
            TableName: !Join [ "-", [ "talr-ops", !Ref stage ] ]
            EncryptionSpecification:
                EncryptionType: KMS
                KMSMasterKeyId: !Ref kmsKey
    dynamodbTableDxInterface:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: divisionDcRegion
                    AttributeType: S
                -
                    AttributeName: vlan
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: divisionDcRegion
                    KeyType: HASH
                -
                    AttributeName: vlan
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: '1'
                WriteCapacityUnits: '1'
            TableName: !Join [ "-", [ "talr-dxInterface", !Ref stage ] ]
            EncryptionSpecification:
                EncryptionType: KMS
                KMSMasterKeyId: !Ref kmsKey
    dynamodbTableClaStatus:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: requestId
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: requestId
                    KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: '1'
                WriteCapacityUnits: '1'
            TableName: !Join [ "-", [ "talr-claStatus", !Ref stage ] ]
            EncryptionSpecification:
                EncryptionType: KMS
                KMSMasterKeyId: !Ref kmsKey
    dynamodbTableConfigRulesCompliance:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                -
                    AttributeName: accountId
                    AttributeType: S
                -
                    AttributeName: pollTimestamp
                    AttributeType: S
            KeySchema:
                -
                    AttributeName: accountId
                    KeyType: HASH
                -
                    AttributeName: pollTimestamp
                    KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: '1'
                WriteCapacityUnits: '1'
            TableName: !Join [ "-", [ "talr-configRulesCompliance", !Ref stage ] ]
            EncryptionSpecification:
                EncryptionType: KMS
                KMSMasterKeyId: !Ref kmsKey

#########
# DynamoDB AutoScaling Role
#########
    dynamodbAutoscalingRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    -
                        Effect: Allow
                        Principal:
                            Service:
                                - application-autoscaling.amazonaws.com
                        Action:
                            - sts:AssumeRole
            Path: "/"
    dynamodbAutoscalingPolicy:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: dynamodbAutoscaling
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                -
                    Effect: Allow
                    Action:
                        - dynamodb:DescribeTable
                        - dynamodb:UpdateTable
                        - cloudwatch:PutMetricAlarm
                        - cloudwatch:DescribeAlarms
                        - cloudwatch:GetMetricStatistics
                        - cloudwatch:SetAlarmState
                        - cloudwatch:DeleteAlarms
                    Resource: "*"
            Roles:
                - !Ref dynamodbAutoscalingRole

#########
# talr-accountInfo AutoScaling Policy
#########
    autoscaleTargetTableAccountInfoTableReadCapacity:
        Type: AWS::ApplicationAutoScaling::ScalableTarget
        Properties:
            MaxCapacity: 10
            MinCapacity: 1
            ResourceId: !Sub table/${dynamodbTableAccountInfo}
            RoleARN: !GetAtt dynamodbAutoscalingRole.Arn
            ScalableDimension: dynamodb:table:ReadCapacityUnits
            ServiceNamespace: dynamodb
    autoscaleTargetTableAccountInfoTableWriteCapacity:
        Type: AWS::ApplicationAutoScaling::ScalableTarget
        Properties:
            MaxCapacity: 10
            MinCapacity: 1
            ResourceId: !Sub table/${dynamodbTableAccountInfo}
            RoleARN: !GetAtt dynamodbAutoscalingRole.Arn
            ScalableDimension: dynamodb:table:WriteCapacityUnits
            ServiceNamespace: dynamodb
    autoscaleTargetTableAccountInfoIndexGsiRequestIdReadCapacity:
        Type: AWS::ApplicationAutoScaling::ScalableTarget
        Properties:
            MaxCapacity: 10
            MinCapacity: 1
            ResourceId: !Sub table/${dynamodbTableAccountInfo}/index/gsiRequestId
            RoleARN: !GetAtt dynamodbAutoscalingRole.Arn
            ScalableDimension: dynamodb:index:ReadCapacityUnits
            ServiceNamespace: dynamodb
    autoscaleTargetTableAccountInfoIndexGsiRequestIdWriteCapacity:
        Type: AWS::ApplicationAutoScaling::ScalableTarget
        Properties:
            MaxCapacity: 10
            MinCapacity: 1
            ResourceId: !Sub table/${